### ISSUE TITLE
FIles 

### ISSUE THREAD

**Issue by alessandroibrahim99** [erdiolmezogullari/ml-time-series-analysis-on-sales-data#1]
Hello,

Where may I download both files sales.txt and article_attributes.txt ?

Thanks
Alex

df_sales = pd.read_csv("sales.txt", sep=";")
df_article = pd.read_csv("article_attributes.txt", sep=";")

**Comment by umang-jain** [comment]
Hey! You found anything yet?

**Comment by 30lm32** [comment]
Hi, it is not a real dataset. I don't have it since I already leave it my old laptop.
You may create it by using sin cos functions with random noise.
